### ISSUE TITLE
Tested update 1.12

### ISSUE THREAD

**Issue by gamagan** [msomeone/PeasyMotion#36] opened 2024-05-25 15:54 UTC
Visual Studio 2022, v17.10

Regarding closed issue #35

I tested the update 1.12 for one character jump (OCJ).

The first issue is fixed -- I can do one char jumps.

The second issue is still there. For me, reproducing this is extremely easy. It would be useful for the dev if another user could reproduce the issue.

Reproduce Steps:

1. Press keyboard shortcut assign to the OCJ command
2. Without doing anything else, press the same keyboard shortcut again.
3. At this point, it's not possible to move with the keyword arrow keys. It seems the mode stays in PeasyMotion OCJ mode -- and it does not get back to regular mode. The only way to get out of that mode is to restart visual studio.

**Comment by msomeone** [comment] 2024-05-25 18:17
Thanks for testing & for repro. I`m unable to reproduce this issue using 'Ctrl+Shift+X' binding for one char jump in regular text editor mode and with VsVim enabled also. But I've reproduced some strange behaviour for double-issuing command for two-char jump, or re-issuing command during two-char jump execution. But to exit jump mode there was no restart required, Esc or some random keybashing was enough... What key-binding was used in your reproducer step #1 and #2? Thanks

**Comment by gamagan** [comment] 2024-05-25 18:27
> What key-binding was used

`Ctrl+T` -- So, for me, it's just `Ctrl+T` followed by `Ctrl+T`.

**Comment by msomeone** [comment] 2024-05-25 20:25
Ctrl+T reproduced the issue. Thanks! Looks like its fixed now

**Closed as completed by msomeone** 2024-05-25 20:25 UTC
